name: Deploy to NuxtHub
on:
  pull_request:
    branches: [dev, main]
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    name: "Deploy to NuxtHub"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/server
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
      url: ${{ steps.deploy.outputs.deployment-url }}
    permissions:
      contents: read
      id-token: write
<<<<<<< HEAD
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
=======

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
<<<<<<< HEAD
>>>>>>> dfa015d (add GitHub Actions workflow for NuxtHub deployment and update nuxt.config for development environment)
=======
>>>>>>> 50dbe23 (add GitHub Actions workflow for NuxtHub deployment and update nuxt.config for development environment)
>>>>>>> efc301e (add GitHub Actions workflow for NuxtHub deployment and update nuxt.config for development environment)

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"

<<<<<<< HEAD
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Deploy with nuxt-hub cli
        run: npx nuxthub deploy
        env:
          NUXT_HUB_PROJECT_KEY: ${{ secrets.NUXT_HUB_PROJECT_KEY}}
          NUXT_HUB_USER_TOKEN: ${{ secrets.NUXT_HUB_USER_TOKEN }}
=======
      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm run build

      - name: Deploy to NuxtHub
        uses: nuxt-hub/action@v1
        id: deploy
<<<<<<< HEAD
>>>>>>> dfa015d (add GitHub Actions workflow for NuxtHub deployment and update nuxt.config for development environment)
=======
>>>>>>> 50dbe23 (add GitHub Actions workflow for NuxtHub deployment and update nuxt.config for development environment)
>>>>>>> efc301e (add GitHub Actions workflow for NuxtHub deployment and update nuxt.config for development environment)
